version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - monitor
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: node.app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    networks:
      - monitor

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - monitor

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - monitor

  fluentd:
    image: fluent/fluentd:v1.16-1
    volumes:
      - ./logging/fluentd.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - monitor

networks:
  monitor:
